### ISSUE TITLE
[Bug] doesnt work

### ISSUE THREAD

**Issue by gabrielmaster123** [3raxton/spicetify-custom-apps-and-extensions#15]
I see the tabs like here 
![image](https://user-images.githubusercontent.com/60442371/114508648-e63e3100-9c34-11eb-884c-76167ecc5b90.png)
but except for lyrics every tab comes out blank and in lyrics it says no lyrics available
![image](https://user-images.githubusercontent.com/60442371/114508759-079f1d00-9c35-11eb-84e2-8deca9190851.png)

Also there arent any buttons like lyrics mode or copy playlist
I am on windows

**Comment by einzigartigerName** [comment]
I think you installed it as custom apps not as extensions.
Are the js files in the extension folder?
And in the Config it should be:
```
extensions = copyPlaylist.js | spotifyLyrics.js
```

**Comment by 3raxton** [comment]
Hey @gabrielmaster123 this is an issue that should be reported on the spicetify-cli repo instead. Check out the spicetify-cli wiki [here](https://github.com/khanhas/spicetify-cli/wiki/Custom-Apps) and repo [here](https://github.com/khanhas/spicetify-cli)!
