### ISSUE TITLE
[Question] Where can i find this theme that you added in podcast hide repo

### ISSUE THREAD

**Issue by milindgoel15** [3raxton/spicetify-custom-apps-and-extensions#25]
![image](https://user-images.githubusercontent.com/45682747/131119227-2dbfed54-6f8b-4028-a888-1ec85b94e089.png)
Taken from here :-
https://github.com/3raxton/spicetify-custom-apps-and-extensions/tree/main/spicetify-hide-podcasts#usage

**Comment by TheGeeKing** [comment]
you should ask to @theRealPadster who is the extension creator https://github.com/theRealPadster/spicetify-hide-podcasts/

**Comment by milindgoel15** [comment]
Ah alright
