### ISSUE TITLE
[META] Clarify whether this repo is for legacy Spotify and Spicetify or not

### ISSUE THREAD

**Issue by Poopooracoocoo** [3raxton/spicetify-custom-apps-and-extensions#26]
**Is your feature request related to a problem? Please describe.**
Users don't know which version of Spotify and Spicetify this repo applies to. 
The community has split between legacy Spotify and Spicetify and the current versions.

**Describe the solution you'd like**
Add something to the repo's readme, description.
This repo could either become only for legacy Spicetify, for v2, or stay a mix of both, with additional labels where appropriate. 

The Community Themes repo specifies that themes are for the latest versions of Spicetify and Spotify: https://github.com/morpheusthewhite/spicetify-themes/tree/master

It also has another branch for legacy Spicetify/Spotify. It's not the greatest approach but no discoverability (a link in the README) was added anyway. Some other projects in communities which have split like this have gone for the other route which is a separate repository.

**Comment by 3raxton** [comment]
Thanks for bringing this up. I agree that this should be implemented and is something I will try to work on in between work and time off. I'll look at the themes repo and find out what works best and add that to this repo. 

I appreciate the patience, and if you're willing to help make this happen, that would be great! An update will come soon!

**Comment by 3raxton** [comment]
Thank you for your suggestion and patience @Poopooracoocoo. The repository has been updated to reflect this suggestion. Check it out [here](https://github.com/3raxton/spicetify-custom-apps-and-extensions/releases/tag/v2.0.0)!
