### ISSUE TITLE
[Enhancement / Feature Request] Add extensions to marketplace

### ISSUE THREAD

**Issue by CharlieS1103** [3raxton/spicetify-custom-apps-and-extensions#28]
Hello! I and @theRealPadster have been working on a custom app for a while now and recently released our first version. It is a marketplace where user's are able to browse and install extensions from within Spotify, we would appreciate it if you added your collection of extensions to it (unless the original owners of the extensions are better suited to doing that, all up to you) 

**Additional context**
https://github.com/CharlieS1103/spicetify-marketplace#manifestjson

**Comment by theRealPadster** [comment]
I'm not sure if there are any that are just hosted on here. I know mine is cross posted but it may be outdated and the original repo is where users should install it from. We wouldn't want two versions to show up. A manifest could be created that only has certain extensions in it, if the others already have their own, perhaps.
